/*
 * This file was generated by the Gradle 'init' task.
 */
import java.util.*
import kotlin.concurrent.thread

plugins {
    java
    kotlin("jvm") version "2.1.10"
    kotlin("plugin.lombok") version "2.1.10"
    id("io.freefair.lombok") version "8.10.2"
    id("com.gradleup.shadow") version "9.0.0-beta4"
}

repositories {
    mavenLocal()
//    mavenCentral()
    maven("https://hub.spigotmc.org/nexus/content/groups/public/")
    maven("https://maven.aliyun.com/nexus/content/groups/public/")
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/") {
        name = "sonatype-oss-snapshots"
    }
    maven("https://repo.panda-lang.org/releases")
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.32")
    implementation("dev.rollczi:litecommands-bukkit:3.9.7")
    annotationProcessor("org.projectlombok:lombok:1.18.32")
    implementation("org.reflections:reflections:0.10.2")
    compileOnly(fileTree(baseDir = "lib"))

}

group = "cn.irina"
version = "1.0"
description = "ThePitAddon"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

kotlin {
    jvmToolchain(17)
}

tasks.compileJava {
    options.compilerArgs.add("-parameters")
}

tasks{
    withType<JavaCompile>() {
        options.encoding = "UTF-8"
        options.compilerArgs.add("-nowarn")
    }

    shadowJar {
        // Delete kotlin metadata
        exclude("**/*.kotlin_metadata")
        exclude("**/*.kotlin_module")
        exclude("**/*.kotlin_builtins")
        exclude("io/netty/**")

        minimize()

        relocate("kotlin", "cn.irina.thirdparty.kotlin")
        relocate("org.reflections", "cn.irina.thirdparty.org.reflections")

        archiveFileName.set("ThePitAddon.jar")
    }

    jar {
        enabled = false
    }

    build {
        dependsOn(shadowJar)
    }
}
