/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    kotlin("jvm") version "2.1.21"
    kotlin("plugin.lombok") version "2.1.10"
    id("io.freefair.lombok") version "8.10.2"
    id("com.gradleup.shadow") version "9.0.0-beta4"
}

repositories {
    mavenLocal()
//    mavenCentral()
    maven("https://hub.spigotmc.org/nexus/content/groups/public/")
    maven("https://maven.aliyun.com/nexus/content/groups/public/")
    maven(url = "https://s01.oss.sonatype.org/content/repositories/snapshots/") {
        name = "sonatype-oss-snapshots"
    }
    maven("https://repo.panda-lang.org/releases")
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.32")
    implementation("dev.rollczi:litecommands-bukkit:3.10.0")
    annotationProcessor("org.projectlombok:lombok:1.18.32")
    implementation("org.reflections:reflections:0.10.2")
    implementation("org.mongojack:mongojack:5.0.0")
    implementation("fastutil:fastutil:5.0.9")
    compileOnly(fileTree(baseDir = "lib"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")

}


group = "cn.irina"
version = "0.0.2"
description = "ThePitAddon-$version"

java {
    sourceCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

kotlin {
    jvmToolchain(17)
}

tasks.compileJava {
    options.compilerArgs.add("-parameters")
}

tasks{
    withType<JavaCompile>() {
        options.encoding = "UTF-8"
        options.compilerArgs.add("-nowarn")
    }

    shadowJar {
        // Delete kotlin metadata
        exclude("**/*.kotlin_metadata")
        exclude("**/*.kotlin_module")
        exclude("**/*.kotlin_builtins")
        exclude("io/netty/**")

        minimize()

        relocate("kotlin", "cn.irina.thirdparty.kotlin")
        relocate("javassist", "cn.irina.thirdparty.javassist")
//        relocate("javax", "cn.irina.thirdparty.javax")
        relocate("org.reflections", "cn.irina.thirdparty.reflections")
        relocate("org.mongojack", "cn.irina.thirdparty.mongojack")
        relocate("org.slf4j", "cn.irina.thirdparty.slf4j")
        relocate("org.jetbrains", "cn.irina.thirdparty.jetbrains")
        relocate("org.bson", "cn.irina.thirdparty.bson")
        relocate("dev.rollczi", "cn.irina.thirdparty.rollczi")
        relocate("com.fasterxml", "cn.irina.thirdparty.fasterxml")
        relocate("com.mongodb", "cn.irina.thirdparty.mongodb")

        relocate("dev.rollczi.litecommands.handler.result", "cn.irina.thirdparty.rollczi.litecommands.handler.result")

        destinationDirectory = file("$projectDir/jar")

        archiveFileName.set("ThePitAddon-$version.jar")
    }

    jar {
        enabled = false
    }

    build {
        dependsOn(shadowJar)
    }
}
